"""Pydantic models for GenAI-driven enhancement planning, iteration tracking,
and explainability reporting.  All models are JSON-serializable and contain
**no** pixel data or PHI – only numeric metrics, issue labels, and text."""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enhancement parameter bounds (safety clamps applied before execution)
# ---------------------------------------------------------------------------

PARAM_BOUNDS: dict[str, tuple[float, float]] = {
    "clahe_clip_limit": (0.005, 0.05),
    "clahe_tile_size": (8, 32),
    "gamma": (0.7, 1.3),
    "unsharp_radius": (0.3, 2.0),
    "unsharp_amount": (0.1, 1.5),
    "post_denoise_strength": (0.0, 0.6),
}


# ---------------------------------------------------------------------------
# Structured output types returned by GenAI agents
# ---------------------------------------------------------------------------


class EnhancementParams(BaseModel):
    """Tunable enhancement parameters.  All values will be clamped to safe
    bounds defined in ``PARAM_BOUNDS`` before execution."""

    clahe_clip_limit: float = Field(
        default=0.015,
        description="CLAHE clip limit (0.005-0.05). Lower = gentler.",
    )
    clahe_tile_size: int = Field(
        default=16,
        description="CLAHE tile/kernel size in pixels (8-32). Larger = smoother.",
    )
    gamma: float = Field(
        default=1.0,
        description="Gamma correction value. <1 brightens shadows, >1 darkens highlights (0.7-1.3).",
    )
    unsharp_radius: float = Field(
        default=0.8,
        description="Unsharp-mask Gaussian radius (0.3-2.0). Smaller = less halo.",
    )
    unsharp_amount: float = Field(
        default=0.5,
        description="Unsharp-mask strength (0.1-1.5). Lower = gentler sharpening.",
    )
    denoise_mode: str = Field(
        default="soft",
        description="Wavelet denoise thresholding mode: 'soft' or 'hard'.",
    )
    post_denoise_strength: float = Field(
        default=0.3,
        description="Post-sharpening denoise blend factor (0.0-0.6). 0 = off.",
    )


class EnhancementPlan(BaseModel):
    """Structured output of the GenAI Planner agent."""

    recommended_ops: list[str] = Field(
        description=(
            "Ordered list of operations to apply. Valid values: "
            "'denoise', 'clahe', 'gamma', 'unsharp', 'post_denoise'."
        ),
    )
    params: EnhancementParams = Field(
        default_factory=EnhancementParams,
        description="Parameter values for enhancement operations.",
    )
    risk_warnings: list[str] = Field(
        default_factory=list,
        description="Potential risks of the proposed enhancement plan.",
    )
    rationale: str = Field(
        default="",
        description="Short explanation of why this plan was chosen.",
    )
    safety: str = Field(
        default="",
        description="What NOT to do — safety guardrail text.",
    )
    stop_reason: Optional[str] = Field(
        default=None,
        description="If non-null, no enhancement is needed and this explains why.",
    )


class IterationRecord(BaseModel):
    """One iteration of the GenAI Tuning agent loop."""

    iteration: int
    plan: EnhancementPlan
    metrics: dict[str, float] = Field(default_factory=dict)
    score: float = 0.0
    chosen: bool = False


class ExplainabilityReport(BaseModel):
    """Clinician-friendly explanation generated by the Explainability agent."""

    detected_issues: str = Field(
        description="What quality issues were detected and their severity.",
    )
    corrective_measures: str = Field(
        description="What corrective measures were suggested and why.",
    )
    enhancement_applied: str = Field(
        description="What enhancement operations were actually applied.",
    )
    validation_outcome: str = Field(
        description="Validation results and their clinical interpretation.",
    )
    limitations: str = Field(
        description="Limitations, caveats, and safe-use warnings.",
    )


class GenAIContext(BaseModel):
    """Non-PHI context passed to GenAI agents.  Never includes pixel data."""

    metrics: dict[str, float] = Field(default_factory=dict)
    issues: list[str] = Field(default_factory=list)
    thresholds: dict[str, float] = Field(default_factory=dict)
    metadata: dict[str, str] = Field(default_factory=dict)
    image_id: str = Field(
        default="original",
        description="In-memory image store key. Never sent to LLM.",
    )
